from paramiko.message import Message as Message
from paramiko.pkey import OPENSSH_AUTH_MAGIC as OPENSSH_AUTH_MAGIC, PKey as PKey
from paramiko.py3compat import b as b
from paramiko.ssh_exception import PasswordRequiredException as PasswordRequiredException, SSHException as SSHException
from typing import Any, Optional

class Ed25519Key(PKey):
    public_blob: Any = ...
    def __init__(self, msg: Optional[Any] = ..., data: Optional[Any] = ..., filename: Optional[Any] = ..., password: Optional[Any] = ..., file_obj: Optional[Any] = ...) -> None: ...
    def asbytes(self): ...
    def __hash__(self) -> Any: ...
    def get_name(self): ...
    def get_bits(self): ...
    def can_sign(self): ...
    def sign_ssh_data(self, data: Any): ...
    def verify_ssh_sig(self, data: Any, msg: Any): ...
