from paramiko import util as util
from paramiko.common import max_byte as max_byte, zero_byte as zero_byte
from paramiko.message import Message as Message
from paramiko.py3compat import byte_chr as byte_chr, byte_mask as byte_mask, long as long
from paramiko.ssh_exception import SSHException as SSHException
from typing import Any

c_MSG_KEXDH_INIT: Any
c_MSG_KEXDH_REPLY: Any
b7fffffffffffffff: Any
b0000000000000000: Any

class KexGroup1:
    P: int = ...
    G: int = ...
    name: str = ...
    hash_algo: Any = ...
    transport: Any = ...
    x: Any = ...
    e: Any = ...
    f: Any = ...
    def __init__(self, transport: Any) -> None: ...
    def start_kex(self) -> None: ...
    def parse_next(self, ptype: Any, m: Any): ...
