from typing import Any

def make_pipe(): ...

class PosixPipe:
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def fileno(self): ...
    def clear(self) -> None: ...
    def set(self) -> None: ...
    def set_forever(self) -> None: ...

class WindowsPipe:
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def fileno(self): ...
    def clear(self) -> None: ...
    def set(self) -> None: ...
    def set_forever(self) -> None: ...

class OrPipe:
    def __init__(self, pipe: Any) -> None: ...
    def set(self) -> None: ...
    def clear(self) -> None: ...

def make_or_pipe(pipe: Any): ...
