from paramiko.ssh_exception import ProxyCommandFailure as ProxyCommandFailure
from paramiko.util import ClosingContextManager as ClosingContextManager
from typing import Any

subprocess: Any
subprocess_import_error: Any

class ProxyCommand(ClosingContextManager):
    cmd: Any = ...
    process: Any = ...
    timeout: Any = ...
    def __init__(self, command_line: Any) -> None: ...
    def send(self, content: Any): ...
    def recv(self, size: Any): ...
    def close(self) -> None: ...
    @property
    def closed(self): ...
    def settimeout(self, timeout: Any) -> None: ...
