import socket
from typing import Any

class SSHException(Exception): ...
class AuthenticationException(SSHException): ...
class PasswordRequiredException(AuthenticationException): ...

class BadAuthenticationType(AuthenticationException):
    allowed_types: Any = ...
    explanation: Any = ...
    def __init__(self, explanation: Any, types: Any) -> None: ...

class PartialAuthentication(AuthenticationException):
    allowed_types: Any = ...
    def __init__(self, types: Any) -> None: ...

class ChannelException(SSHException):
    code: Any = ...
    text: Any = ...
    def __init__(self, code: Any, text: Any) -> None: ...

class BadHostKeyException(SSHException):
    hostname: Any = ...
    key: Any = ...
    expected_key: Any = ...
    def __init__(self, hostname: Any, got_key: Any, expected_key: Any) -> None: ...

class ProxyCommandFailure(SSHException):
    command: Any = ...
    error: Any = ...
    def __init__(self, command: Any, error: Any) -> None: ...

class NoValidConnectionsError(socket.error):
    errors: Any = ...
    def __init__(self, errors: Any) -> None: ...
    def __reduce__(self): ...

class CouldNotCanonicalize(SSHException): ...
class ConfigParseError(SSHException): ...
