from paramiko.message import Message as Message
from paramiko.py3compat import byte_chr as byte_chr, long as long
from paramiko.ssh_exception import SSHException as SSHException
from typing import Any

c_MSG_KEXECDH_INIT: Any
c_MSG_KEXECDH_REPLY: Any

class KexNistp256:
    name: str = ...
    hash_algo: Any = ...
    curve: Any = ...
    transport: Any = ...
    P: Any = ...
    Q_C: Any = ...
    Q_S: Any = ...
    def __init__(self, transport: Any) -> None: ...
    def start_kex(self) -> None: ...
    def parse_next(self, ptype: Any, m: Any): ...

class KexNistp384(KexNistp256):
    name: str = ...
    hash_algo: Any = ...
    curve: Any = ...

class KexNistp521(KexNistp256):
    name: str = ...
    hash_algo: Any = ...
    curve: Any = ...
