from paramiko import util as util
from paramiko.common import asbytes as asbytes, max_byte as max_byte, one_byte as one_byte, zero_byte as zero_byte
from paramiko.py3compat import BytesIO as BytesIO, integer_types as integer_types, long as long, u as u
from typing import Any, Optional

class Message:
    big_int: Any = ...
    packet: Any = ...
    def __init__(self, content: Optional[Any] = ...) -> None: ...
    def asbytes(self): ...
    def rewind(self) -> None: ...
    def get_remainder(self): ...
    def get_so_far(self): ...
    def get_bytes(self, n: Any): ...
    def get_byte(self): ...
    def get_boolean(self): ...
    def get_adaptive_int(self): ...
    def get_int(self): ...
    def get_int64(self): ...
    def get_mpint(self): ...
    def get_string(self): ...
    def get_text(self): ...
    def get_binary(self): ...
    def get_list(self): ...
    def add_bytes(self, b: Any): ...
    def add_byte(self, b: Any): ...
    def add_boolean(self, b: Any): ...
    def add_int(self, n: Any): ...
    def add_adaptive_int(self, n: Any): ...
    def add_int64(self, n: Any): ...
    def add_mpint(self, z: Any): ...
    def add_string(self, s: Any): ...
    def add_list(self, l: Any): ...
    def add(self, *seq: Any) -> None: ...
