from paramiko.py3compat import PY2 as PY2, b as b
from typing import Any, Optional

class PipeTimeout(IOError): ...

class BufferedPipe:
    def __init__(self) -> None: ...
    def set_event(self, event: Any) -> None: ...
    def feed(self, data: Any) -> None: ...
    def read_ready(self): ...
    def read(self, nbytes: Any, timeout: Optional[Any] = ...): ...
    def empty(self): ...
    def close(self) -> None: ...
    def __len__(self): ...
