from typing import Any

class ZlibCompressor:
    z: Any = ...
    def __init__(self) -> None: ...
    def __call__(self, data: Any): ...

class ZlibDecompressor:
    z: Any = ...
    def __init__(self) -> None: ...
    def __call__(self, data: Any): ...
