from .py3compat import StringIO as StringIO
from .ssh_exception import ConfigParseError as ConfigParseError, CouldNotCanonicalize as CouldNotCanonicalize
from typing import Any, Optional

invoke: Any
invoke_import_error: Any
SSH_PORT: int

class SSHConfig:
    SETTINGS_REGEX: Any = ...
    TOKENS_BY_CONFIG_KEY: Any = ...
    def __init__(self) -> None: ...
    @classmethod
    def from_text(cls, text: Any): ...
    @classmethod
    def from_path(cls, path: Any): ...
    @classmethod
    def from_file(cls, flo: Any): ...
    def parse(self, file_obj: Any) -> None: ...
    def lookup(self, hostname: Any): ...
    def canonicalize(self, hostname: Any, options: Any, domains: Any): ...
    def get_hostnames(self): ...

class LazyFqdn:
    fqdn: Any = ...
    config: Any = ...
    host: Any = ...
    def __init__(self, config: Any, host: Optional[Any] = ...) -> None: ...

class SSHConfigDict(dict):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def as_bool(self, key: Any): ...
    def as_int(self, key: Any): ...
