from paramiko.kex_group1 import KexGroup1 as KexGroup1
from typing import Any

class KexGroup14(KexGroup1):
    P: int = ...
    G: int = ...
    name: str = ...
    hash_algo: Any = ...

class KexGroup14SHA256(KexGroup14):
    name: str = ...
    hash_algo: Any = ...
