from paramiko import util as util
from paramiko.common import DEBUG as DEBUG, max_byte as max_byte, zero_byte as zero_byte
from paramiko.message import Message as Message
from paramiko.py3compat import byte_chr as byte_chr, byte_mask as byte_mask, byte_ord as byte_ord
from paramiko.ssh_exception import SSHException as SSHException
from typing import Any

MSG_KEXGSS_INIT: Any
MSG_KEXGSS_CONTINUE: Any
MSG_KEXGSS_COMPLETE: Any
MSG_KEXGSS_HOSTKEY: Any
MSG_KEXGSS_ERROR: Any
MSG_KEXGSS_GROUPREQ: Any
MSG_KEXGSS_GROUP: Any
c_MSG_KEXGSS_INIT: Any
c_MSG_KEXGSS_CONTINUE: Any
c_MSG_KEXGSS_COMPLETE: Any
c_MSG_KEXGSS_HOSTKEY: Any
c_MSG_KEXGSS_ERROR: Any
c_MSG_KEXGSS_GROUPREQ: Any
c_MSG_KEXGSS_GROUP: Any

class KexGSSGroup1:
    P: int = ...
    G: int = ...
    b7fffffffffffffff: Any = ...
    b0000000000000000: Any = ...
    NAME: str = ...
    transport: Any = ...
    kexgss: Any = ...
    gss_host: Any = ...
    x: int = ...
    e: int = ...
    f: int = ...
    def __init__(self, transport: Any) -> None: ...
    def start_kex(self) -> None: ...
    def parse_next(self, ptype: Any, m: Any): ...

class KexGSSGroup14(KexGSSGroup1):
    P: int = ...
    G: int = ...
    NAME: str = ...

class KexGSSGex:
    NAME: str = ...
    min_bits: int = ...
    max_bits: int = ...
    preferred_bits: int = ...
    transport: Any = ...
    kexgss: Any = ...
    gss_host: Any = ...
    p: Any = ...
    q: Any = ...
    g: Any = ...
    x: Any = ...
    e: Any = ...
    f: Any = ...
    old_style: bool = ...
    def __init__(self, transport: Any) -> None: ...
    def start_kex(self) -> None: ...
    def parse_next(self, ptype: Any, m: Any): ...

class NullHostKey:
    key: str = ...
    def __init__(self) -> None: ...
    def get_name(self): ...
