from paramiko import util as util
from paramiko.common import DEBUG as DEBUG
from paramiko.message import Message as Message
from paramiko.py3compat import byte_chr as byte_chr, byte_mask as byte_mask, byte_ord as byte_ord
from paramiko.ssh_exception import SSHException as SSHException
from typing import Any

c_MSG_KEXDH_GEX_REQUEST_OLD: Any
c_MSG_KEXDH_GEX_GROUP: Any
c_MSG_KEXDH_GEX_INIT: Any
c_MSG_KEXDH_GEX_REPLY: Any
c_MSG_KEXDH_GEX_REQUEST: Any

class KexGex:
    name: str = ...
    min_bits: int = ...
    max_bits: int = ...
    preferred_bits: int = ...
    hash_algo: Any = ...
    transport: Any = ...
    p: Any = ...
    q: Any = ...
    g: Any = ...
    x: Any = ...
    e: Any = ...
    f: Any = ...
    old_style: bool = ...
    def __init__(self, transport: Any) -> None: ...
    def start_kex(self, _test_old_style: bool = ...) -> None: ...
    def parse_next(self, ptype: Any, m: Any): ...

class KexGexSHA256(KexGex):
    name: str = ...
    hash_algo: Any = ...
