from paramiko import util as util
from paramiko.py3compat import byte_mask as byte_mask, long as long
from paramiko.ssh_exception import SSHException as SSHException
from typing import Any

class ModulusPack:
    pack: Any = ...
    discarded: Any = ...
    def __init__(self) -> None: ...
    def read_file(self, filename: Any) -> None: ...
    def get_modulus(self, min: Any, prefer: Any, max: Any): ...
