from paramiko.common import o70 as o70, o700 as o700, x80000000 as x80000000, xffffffff as xffffffff
from paramiko.py3compat import b as b, long as long
from typing import Any, Optional

class SFTPAttributes:
    FLAG_SIZE: int = ...
    FLAG_UIDGID: int = ...
    FLAG_PERMISSIONS: int = ...
    FLAG_AMTIME: int = ...
    FLAG_EXTENDED: Any = ...
    st_size: Any = ...
    st_uid: Any = ...
    st_gid: Any = ...
    st_mode: Any = ...
    st_atime: Any = ...
    st_mtime: Any = ...
    attr: Any = ...
    def __init__(self) -> None: ...
    @classmethod
    def from_stat(cls, obj: Any, filename: Optional[Any] = ...): ...
    def asbytes(self): ...
