from paramiko.sftp import SFTP_OK as SFTP_OK, SFTP_OP_UNSUPPORTED as SFTP_OP_UNSUPPORTED
from paramiko.sftp_server import SFTPServer as SFTPServer
from paramiko.util import ClosingContextManager as ClosingContextManager
from typing import Any

class SFTPHandle(ClosingContextManager):
    def __init__(self, flags: int = ...) -> None: ...
    def close(self) -> None: ...
    def read(self, offset: Any, length: Any): ...
    def write(self, offset: Any, data: Any): ...
    def stat(self): ...
    def chattr(self, attr: Any): ...
