from paramiko.sftp import SFTP_OP_UNSUPPORTED as SFTP_OP_UNSUPPORTED
from typing import Any

class SFTPServerInterface:
    def __init__(self, server: Any, *largs: Any, **kwargs: Any) -> None: ...
    def session_started(self) -> None: ...
    def session_ended(self) -> None: ...
    def open(self, path: Any, flags: Any, attr: Any): ...
    def list_folder(self, path: Any): ...
    def stat(self, path: Any): ...
    def lstat(self, path: Any): ...
    def remove(self, path: Any): ...
    def rename(self, oldpath: Any, newpath: Any): ...
    def posix_rename(self, oldpath: Any, newpath: Any): ...
    def mkdir(self, path: Any, attr: Any): ...
    def rmdir(self, path: Any): ...
    def chattr(self, path: Any, attr: Any): ...
    def canonicalize(self, path: Any): ...
    def readlink(self, path: Any): ...
    def symlink(self, target_path: Any, path: Any): ...
